### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by daniel22390** [jmmccota/Otim-Tp1#2]
Ao carregar um problema e tentar carregar outro problema, o conteudo das abas somem. Corrigido

**Comment by daniel22390** [comment]
Ao colocar 10 variaveis, os valores estoram o tamanho da div de solução.

**Comment by daniel22390** [comment]
No modelo(12) que esta no grupo do face, não aparece o modelo de programação linear

**Comment by daniel22390** [comment]
Em alguns casos qdo mostra a função objetivo, os valores positivos não aparecem

**Comment by jmmccota** [comment]
errado!!
