### ISSUE TITLE
Mais bugs

### ISSUE THREAD

**Issue by daniel22390** [jmmccota/Otim-Tp1#3]
Pagina de modelo nao abre - Consertado

**Comment by daniel22390** [comment]
os limites inferioresa e superiores estao aceitando valores como innnnnnnffffffffffff

**Comment by daniel22390** [comment]
o modelo de programação linear tomou chá de sumiço

**Comment by daniel22390** [comment]
no executar passo a passo, quando vai clicar no x a ser ramificado, parece q da um zoom no valor do x... isso atrapalha o usuario a clicar...

**Comment by daniel22390** [comment]
Ao colocar valor real com separador vírgula(Ex.: 3,5) no limite superior ou limite inferior, ele não reconhece a expressão

**Comment by daniel22390** [comment]
Com valores reais não está retornando o objetivo correto, parece q ele está lendo apenas a parte inteira

**Comment by andrmalta** [comment]
Quando bug tiver consertado fecha ele

**Comment by jmmccota** [comment]
errado!
