### ISSUE TITLE
Estouro de DIV

### ISSUE THREAD

**Issue by jmmccota** [jmmccota/Otim-Tp1#4]
Ao colocar 10 variaveis, os valores estoram o tamanho da div de solução.

**Comment by andremalta-dev** [comment]
esse bug n tem como mexer, ou fica assim ou a arvore fica menor

**Comment by EliasLuiz** [comment]
E se a gente aumentasse a div que fica a tabela e o resultado?

**Comment by andremalta-dev** [comment]
ja ta no tamanho maximo,
